# Generated by Django 4.0.3 on 2022-04-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_cattoy'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinchToy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='CatToy',
        ),
        migrations.AddField(
            model_name='finch',
            name='cattoys',
            field=models.ManyToManyField(to='main_app.finchtoy'),
        ),
    ]
