# Generated by Django 4.0.3 on 2022-04-02 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_finchtoy_delete_cattoy_finch_cattoys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finch',
            old_name='cattoys',
            new_name='finchtoys',
        ),
    ]
